package modelo;

/**
 * Enumeradores para provincias de Chile
 * @author Sebastián Pavez
 */
public enum Provincias {
    Arica, 
    Parinacota, 
    Iquique, 
    Tamarugal, 
    Antofagasta, 
    Loa, 
    Tocopilla, 
    Copiapo, 
    Chañaral, 
    Huasco, 
    Elqui, 
    Choapa, 
    Limari, 
    Valparaiso, 
    IslaPascua, 
    LosAndes, 
    Petorca, 
    Quillota,
    SanAntonio,
    SanFelipe,
    MargaMarga,
    Cachapoal,
    CardenalCaro,
    Colchagua,
    Talca,
    Cauquenes,
    Curico,
    Linares,
    Concepcion,
    Arauco,
    Biobio,
    Ñuble,
    Cautin,
    Malleco,
    Valdivia,
    Ranco,
    Llanquihue,
    Chiloe,
    Osorno,
    Palena,
    Coihaique,
    Aisen,
    CapitanPrat,
    GeneralCarrera,
    Magallanes,
    Antartica,
    TierraDelFuego,
    UltimaEsperanza,
    Santiago,
    Cordillera,
    Chacabuco,
    Maipo,
    Melipilla,
    Talagante;
   
}
